### PR TITLE
[FEAT] Add Search Bar

### LINKED ISSUE #18: [FEAT] Add search bar
We want to add our own search bar where we can search data as follows

-  GitHub username
- Name of the user

### PR DESCRIPTION
**Pull request by Rishav1707**
**Description**

**Fixes Issue**

This PR fixes the following issues:

closes #18

**Proposed Changes**

Here comes all the changes proposed through this PR
- Added `Search.jsx` file.
- Some changes in the CSS file.
- Navbar is modified with the search bar.

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

https://user-images.githubusercontent.com/97666287/228743291-74d59caa-2709-416d-b38c-2abda7656326.mp4

### CODE REVIEW

**Comment by himanshu1221** [comment]
> **Description**
> 
> **Fixes Issue**
> 
> This PR fixes the following issues:
> 
> closes #18
> 
> **Proposed Changes**
> 
> Here comes all the changes proposed through this PR
> 
> * Added `Search.jsx` file.
> * Some changes in the CSS file.
> * Navbar is modified with the search bar.
> 
> ## Check List (Check all the boxes which are applicable)
> * [x]  My code follows the code style of this project.
> * [ ]  My change requires a change to the documentation.
> * [ ]  I have updated the documentation accordingly.
> * [x]  All new and existing tests passed.
> * [x]  This PR does not contain plagiarized content.
> * [x]  The title of my pull request is a short description of the requested changes.
> 
> ## Screenshots

hey @Rishav1707 I want to route to the particular user whose data is available in `public/data` and for the same the link is here `https://linkfree-clone.vercel.app/himanshu1221`

**Comment by Rishav1707** [comment]
> > **Description**
> > **Fixes Issue**
> > This PR fixes the following issues:
> > closes #18
> > **Proposed Changes**
> > Here comes all the changes proposed through this PR
> > 
> > * Added `Search.jsx` file.
> > * Some changes in the CSS file.
> > * Navbar is modified with the search bar.
> > 
> > ## Check List (Check all the boxes which are applicable)
> > 
> > * [x]   My code follows the code style of this project.
> > * [ ]   My change requires a change to the documentation.
> > * [ ]   I have updated the documentation accordingly.
> > * [x]   All new and existing tests passed.
> > * [x]   This PR does not contain plagiarized content.
> > * [x]   The title of my pull request is a short description of the requested changes.
> > 
> > ## Screenshots
> 
> hey @Rishav1707 I want to route to the particular user whose data is available in `public/data` and for the same the link is here `https://linkfree-clone.vercel.app/himanshu1221`

Sure, I will let you know after making the changes

**Comment by Rishav1707** [comment]
> > **Description**
> > **Fixes Issue**
> > This PR fixes the following issues:
> > closes #18
> > **Proposed Changes**
> > Here comes all the changes proposed through this PR
> > 
> > * Added `Search.jsx` file.
> > * Some changes in the CSS file.
> > * Navbar is modified with the search bar.
> > 
> > ## Check List (Check all the boxes which are applicable)
> > 
> > * [x]   My code follows the code style of this project.
> > * [ ]   My change requires a change to the documentation.
> > * [ ]   I have updated the documentation accordingly.
> > * [x]   All new and existing tests passed.
> > * [x]   This PR does not contain plagiarized content.
> > * [x]   The title of my pull request is a short description of the requested changes.
> > 
> > ## Screenshots
> 
> hey @Rishav1707 I want to route to the particular user whose data is available in `public/data` and for the same the link is here `https://linkfree-clone.vercel.app/himanshu1221`

I have made some changes, let me know if any changes you want

**Comment by Rishav1707** [comment]
> > > **Description**
> > > **Fixes Issue**
> > > This PR fixes the following issues:
> > > closes #18
> > > **Proposed Changes**
> > > Here comes all the changes proposed through this PR
> > > 
> > > * Added `Search.jsx` file.
> > > * Some changes in the CSS file.
> > > * Navbar is modified with the search bar.
> > > 
> > > ## Check List (Check all the boxes which are applicable)
> > > 
> > > * [x]    My code follows the code style of this project.
> > > * [ ]    My change requires a change to the documentation.
> > > * [ ]    I have updated the documentation accordingly.
> > > * [x]    All new and existing tests passed.
> > > * [x]    This PR does not contain plagiarized content.
> > > * [x]    The title of my pull request is a short description of the requested changes.
> > > 
> > > ## Screenshots
> > 
> > 
> > hey @Rishav1707 I want to route to the particular user whose data is available in `public/data` and for the same the link is here `https://linkfree-clone.vercel.app/himanshu1221`
> 
> I have made some changes, let me know if any changes you want

@himanshu1221 Review my PR

**Review by himanshu1221 — APPROVED** [review]
Awesome LGTM :+1:

**Pull request merged**
