### PR TITLE
Added dark mode

### PR DESCRIPTION
**Pull request by Palakkgoyal**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Palakkgoyal** [comment]
Hey, I got messed up in the previous branch. But in this branch I have resolved the issue

**Comment by himanshu1221** [comment]
> Hey, I got messed up in the previous branch. But in this branch I have resolved the issue

Hey @Palakkgoyal text colour is changing but the background colour is not changing kindly look into this 

[linkfree bug.webm](https://user-images.githubusercontent.com/32031706/229265514-3cc26734-2404-4d89-99b7-e8224c2c1d33.webm)

**Comment by Palakkgoyal** [comment]
Hey check the changes

**Comment by Palakkgoyal** [comment]
Hello, @himanshu1221 have you checked?

**Review by himanshu1221 — APPROVED** [review]
Awesome looks good to me

**Pull request merged**
